import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Form from '../components/Form'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Isiah Hale | Videographer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Contact />
     
      
      
    </div>
   
  )
}
